# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['document', 'ordering']},
        ),
        migrations.AddField(
            model_name='question',
            name='code',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='code_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='ordering',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
