# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 16:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('risk', '0001_initial'), ('risk', '0002_auto_20160612_1701'), ('risk', '0003_auto_20160613_0628'), ('risk', '0004_control_activity_help'), ('risk', '0005_auto_20160613_0835'), ('risk', '0006_auto_20160613_0837'), ('risk', '0007_auto_20160613_1005'), ('risk', '0008_auto_20160613_1018'), ('risk', '0009_auto_20160614_0811'), ('risk', '0010_auto_20160614_1352'), ('risk', '0011_auto_20160614_1414')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField()),
                ('area', models.CharField(choices=[('G', 'Governance'), ('M', 'Management')], default='M', max_length=1)),
                ('domain', models.CharField(max_length=75)),
                ('process_id', models.CharField(max_length=15)),
                ('process_name', models.CharField(blank=True, max_length=200)),
                ('process_description', models.CharField(blank=True, max_length=200)),
                ('process_purpose', models.CharField(blank=True, max_length=200)),
                ('practice_id', models.CharField(max_length=15)),
                ('practice_name', models.CharField(max_length=100)),
                ('practice_governance', models.CharField(blank=True, max_length=200)),
                ('activity_id', models.CharField(blank=True, max_length=15)),
                ('activity', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['standard', 'ordering'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField()),
                ('code', models.CharField(max_length=15)),
                ('code_text', models.TextField()),
                ('text', models.TextField()),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['standard', 'ordering'],
            },
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SelectionQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('A', 'Accept'), ('M', 'Mitigate'), ('T', 'Transfer'), ('O', 'Avoid')], default='A', max_length=1)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.Question')),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.Selection')),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='selection',
            name='standards',
            field=models.ManyToManyField(blank=True, to='risk.Standard'),
        ),
        migrations.AddField(
            model_name='control',
            name='standard',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='risk.Standard'),
        ),
        migrations.AlterUniqueTogether(
            name='selectionquestion',
            unique_together=set([]),
        ),
        migrations.AddField(
            model_name='control',
            name='domain_en',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='domain_nl',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='process_name_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='process_name_nl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='activity',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='domain',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='control',
            name='practice_id',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='control',
            name='practice_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='control',
            name='process_id',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='control',
            name='activity_help',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='process_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='process_purpose',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='practice_governance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='control',
            name='activity_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='activity_help_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='activity_help_nl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='activity_nl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='practice_governance_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='practice_governance_nl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='practice_name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='practice_name_nl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='process_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='process_description_nl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='process_purpose_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='process_purpose_nl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='activity_id',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='Impact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('descriptor', models.CharField(max_length=30, unique=True)),
                ('definition', models.TextField()),
            ],
            options={
                'ordering': ['rating'],
            },
        ),
        migrations.CreateModel(
            name='Likelyhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('descriptor', models.CharField(max_length=30, unique=True)),
                ('definition', models.TextField()),
            ],
            options={
                'ordering': ['rating'],
            },
        ),
        migrations.CreateModel(
            name='SelectionControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('A', 'Accept'), ('M', 'Mitigate'), ('T', 'Transfer'), ('O', 'Avoid')], default='A', max_length=1)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.Control')),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.Selection')),
            ],
        ),
        migrations.RemoveField(
            model_name='selectionquestion',
            name='question',
        ),
        migrations.RemoveField(
            model_name='selectionquestion',
            name='selection',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='SelectionQuestion',
        ),
        migrations.AlterUniqueTogether(
            name='selectioncontrol',
            unique_together=set([('selection', 'control')]),
        ),
        migrations.CreateModel(
            name='RiskMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('is_template', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='impact',
            name='riskmap',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='risk.RiskMap'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='likelyhood',
            name='riskmap',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='risk.RiskMap'),
            preserve_default=False,
        ),
    ]
