# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 16:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField()),
                ('area', models.CharField(choices=[('G', 'Governance'), ('M', 'Management')], default='M', max_length=1)),
                ('domain', models.CharField(blank=True, max_length=75)),
                ('domain_en', models.CharField(blank=True, max_length=75, null=True)),
                ('domain_nl', models.CharField(blank=True, max_length=75, null=True)),
                ('process_id', models.CharField(blank=True, max_length=15)),
                ('process_name', models.CharField(blank=True, max_length=200)),
                ('process_name_en', models.CharField(blank=True, max_length=200, null=True)),
                ('process_name_nl', models.CharField(blank=True, max_length=200, null=True)),
                ('process_description', models.TextField(blank=True)),
                ('process_description_en', models.TextField(blank=True, null=True)),
                ('process_description_nl', models.TextField(blank=True, null=True)),
                ('process_purpose', models.TextField(blank=True)),
                ('process_purpose_en', models.TextField(blank=True, null=True)),
                ('process_purpose_nl', models.TextField(blank=True, null=True)),
                ('practice_id', models.CharField(blank=True, max_length=15)),
                ('practice_name', models.CharField(blank=True, max_length=100)),
                ('practice_name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('practice_name_nl', models.CharField(blank=True, max_length=100, null=True)),
                ('practice_governance', models.TextField(blank=True)),
                ('practice_governance_en', models.TextField(blank=True, null=True)),
                ('practice_governance_nl', models.TextField(blank=True, null=True)),
                ('activity_id', models.CharField(max_length=15)),
                ('activity', models.TextField(blank=True)),
                ('activity_en', models.TextField(blank=True, null=True)),
                ('activity_nl', models.TextField(blank=True, null=True)),
                ('activity_help', models.TextField(blank=True)),
                ('activity_help_en', models.TextField(blank=True, null=True)),
                ('activity_help_nl', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['standard', 'ordering'],
            },
        ),
        migrations.CreateModel(
            name='Impact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('descriptor', models.CharField(max_length=30, unique=True)),
                ('definition', models.TextField()),
            ],
            options={
                'ordering': ['rating'],
            },
        ),
        migrations.CreateModel(
            name='Likelyhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('descriptor', models.CharField(max_length=30, unique=True)),
                ('definition', models.TextField()),
            ],
            options={
                'ordering': ['rating'],
            },
        ),
        migrations.CreateModel(
            name='RiskMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('is_template', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SelectionControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('A', 'Accept'), ('M', 'Mitigate'), ('T', 'Transfer'), ('O', 'Avoid')], default='A', max_length=1)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.Control')),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.Selection')),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='selection',
            name='standards',
            field=models.ManyToManyField(blank=True, to='risk.Standard'),
        ),
        migrations.AddField(
            model_name='likelyhood',
            name='riskmap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.RiskMap'),
        ),
        migrations.AddField(
            model_name='impact',
            name='riskmap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.RiskMap'),
        ),
        migrations.AddField(
            model_name='control',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.Standard'),
        ),
        migrations.AlterUniqueTogether(
            name='selectioncontrol',
            unique_together=set([('selection', 'control')]),
        ),
    ]
