# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField()),
                ('area', models.CharField(choices=[('G', 'Governance'), ('M', 'Management')], default='M', max_length=1)),
                ('domain', models.CharField(max_length=75)),
                ('process_id', models.CharField(max_length=15)),
                ('process_name', models.CharField(blank=True, max_length=200)),
                ('process_description', models.CharField(blank=True, max_length=200)),
                ('process_purpose', models.CharField(blank=True, max_length=200)),
                ('practice_id', models.CharField(max_length=15)),
                ('practice_name', models.CharField(max_length=100)),
                ('practice_governance', models.CharField(blank=True, max_length=200)),
                ('activity_id', models.CharField(blank=True, max_length=15)),
                ('activity', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['standard', 'ordering'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField()),
                ('code', models.CharField(max_length=15)),
                ('code_text', models.TextField()),
                ('text', models.TextField()),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['standard', 'ordering'],
            },
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SelectionQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('A', 'Accept'), ('M', 'Mitigate'), ('T', 'Transfer'), ('O', 'Avoid')], default='A', max_length=1)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.Question')),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.Selection')),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='selection',
            name='standards',
            field=models.ManyToManyField(blank=True, to='risk.Standard'),
        ),
        migrations.AddField(
            model_name='question',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.Standard'),
        ),
        migrations.AddField(
            model_name='control',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='risk.Standard'),
        ),
        migrations.AlterUniqueTogether(
            name='selectionquestion',
            unique_together=set([('selection', 'question')]),
        ),
    ]
