# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='domain_en',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='domain_nl',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='process_name_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='process_name_nl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
