# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0002_auto_20160612_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='activity',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='domain',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='control',
            name='domain_en',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='domain_nl',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='practice_id',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='control',
            name='practice_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='control',
            name='process_id',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
