# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0002_company_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name']},
        ),
    ]
