# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0003_auto_20160627_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='risk.Company'),
            preserve_default=False,
        ),
    ]
