# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0003_auto_20160613_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='activity_help',
            field=models.TextField(blank=True),
        ),
    ]
