# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0004_selection_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField()),
                ('activity_id', models.CharField(max_length=15)),
                ('activity', models.TextField(blank=True)),
                ('activity_en', models.TextField(blank=True, null=True)),
                ('activity_nl', models.TextField(blank=True, null=True)),
                ('activity_help', models.TextField(blank=True)),
                ('activity_help_en', models.TextField(blank=True, null=True)),
                ('activity_help_nl', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ControlDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField()),
                ('area', models.CharField(choices=[('G', 'Governance'), ('M', 'Management')], default='M', max_length=1)),
                ('domain', models.CharField(blank=True, max_length=75)),
                ('domain_en', models.CharField(blank=True, max_length=75, null=True)),
                ('domain_nl', models.CharField(blank=True, max_length=75, null=True)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.Standard')),
            ],
            options={
                'ordering': ['standard', 'domain'],
            },
        ),
        migrations.CreateModel(
            name='ControlPractice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField()),
                ('practice_id', models.CharField(blank=True, max_length=15)),
                ('practice_name', models.CharField(blank=True, max_length=100)),
                ('practice_name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('practice_name_nl', models.CharField(blank=True, max_length=100, null=True)),
                ('practice_governance', models.TextField(blank=True)),
                ('practice_governance_en', models.TextField(blank=True, null=True)),
                ('practice_governance_nl', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ControlProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField()),
                ('process_id', models.CharField(blank=True, max_length=15)),
                ('process_name', models.CharField(blank=True, max_length=200)),
                ('process_name_en', models.CharField(blank=True, max_length=200, null=True)),
                ('process_name_nl', models.CharField(blank=True, max_length=200, null=True)),
                ('process_description', models.TextField(blank=True)),
                ('process_description_en', models.TextField(blank=True, null=True)),
                ('process_description_nl', models.TextField(blank=True, null=True)),
                ('process_purpose', models.TextField(blank=True)),
                ('process_purpose_en', models.TextField(blank=True, null=True)),
                ('process_purpose_nl', models.TextField(blank=True, null=True)),
                ('controldomain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.ControlDomain')),
            ],
        ),
        migrations.RemoveField(
            model_name='control',
            name='standard',
        ),
        migrations.AlterField(
            model_name='selectioncontrol',
            name='control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.ControlActivity'),
        ),
        migrations.DeleteModel(
            name='Control',
        ),
        migrations.AddField(
            model_name='controlpractice',
            name='controlprocess',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.ControlProcess'),
        ),
        migrations.AddField(
            model_name='controlactivity',
            name='controlpractice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.ControlPractice'),
        ),
    ]
