# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0004_control_activity_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='process_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='process_purpose',
            field=models.TextField(blank=True),
        ),
    ]
