# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0004_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='name',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
