# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0005_auto_20160628_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenarios',
            fields=[
                ('reference', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('risk_scenario', models.TextField()),
                ('threat_type', models.TextField()),
                ('actor', models.TextField()),
                ('event', models.TextField()),
                ('cause', models.TextField()),
                ('effect', models.TextField()),
                ('time', models.TextField()),
                ('it_benefit', models.CharField(choices=[('N/A', 'Not Available'), ('p', 'Primary'), ('S', 'Secondary')], default='N/A', max_length=3)),
                ('it_programme', models.CharField(choices=[('N/A', 'Not Available'), ('p', 'Primary'), ('S', 'Secondary')], default='N/A', max_length=3)),
                ('it_operations', models.CharField(choices=[('N/A', 'Not Available'), ('p', 'Primary'), ('S', 'Secondary')], default='N/A', max_length=3)),
                ('avoidance', models.TextField()),
                ('acceptance', models.TextField()),
                ('transfer', models.TextField()),
                ('mitigation', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='controlactivity',
            options={'ordering': ['controlpractice__controlprocess__controldomain__standard', 'controlpractice__controlprocess__controldomain__ordering', 'controlpractice__controlprocess__ordering', 'controlpractice__ordering', 'ordering'], 'verbose_name_plural': 'Control activities'},
        ),
        migrations.AlterModelOptions(
            name='controldomain',
            options={'ordering': ['standard', 'ordering']},
        ),
        migrations.AlterModelOptions(
            name='controlpractice',
            options={'ordering': ['controlprocess__controldomain__standard', 'controlprocess__controldomain__ordering', 'controlprocess__ordering', 'ordering']},
        ),
        migrations.AlterModelOptions(
            name='controlprocess',
            options={'ordering': ['controldomain__standard', 'controldomain__ordering', 'ordering'], 'verbose_name_plural': 'Control processes'},
        ),
    ]
