# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0006_auto_20160708_1230'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scenarios',
            new_name='Scenario',
        ),
    ]
