# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0006_auto_20160613_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='activity_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='activity_help_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='activity_help_nl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='activity_nl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='practice_governance_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='practice_governance_nl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='practice_name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='practice_name_nl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='process_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='process_description_nl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='process_purpose_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='process_purpose_nl',
            field=models.TextField(blank=True, null=True),
        ),
    ]
