# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0007_auto_20160708_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioCategory',
            fields=[
                ('nr', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['nr'],
            },
        ),
        migrations.AlterModelOptions(
            name='scenario',
            options={'ordering': ['reference']},
        ),
        migrations.AddField(
            model_name='scenario',
            name='negative',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='positive',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.ScenarioCategory'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='it_benefit',
            field=models.CharField(choices=[('N/A', 'Not Available'), ('P', 'Primary'), ('S', 'Secondary')], default='N/A', max_length=3),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='it_operations',
            field=models.CharField(choices=[('N/A', 'Not Available'), ('P', 'Primary'), ('S', 'Secondary')], default='N/A', max_length=3),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='it_programme',
            field=models.CharField(choices=[('N/A', 'Not Available'), ('P', 'Primary'), ('S', 'Secondary')], default='N/A', max_length=3),
        ),
    ]
