# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0007_auto_20160613_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='standard',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='risk.Standard'),
            preserve_default=False,
        ),
    ]
