# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 07:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0008_auto_20160708_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scenariocategory',
            options={'ordering': ['nr'], 'verbose_name_plural': 'scenario categories'},
        ),
    ]
