# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0008_auto_20160613_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='activity_id',
            field=models.CharField(max_length=15),
        ),
    ]
