# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-27 15:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0009_auto_20160711_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='likelyhood',
            name='max_value',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='impact',
            name='descriptor',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='impact',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='likelyhood',
            name='descriptor',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='likelyhood',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(3)]),
        ),
        migrations.AlterUniqueTogether(
            name='impact',
            unique_together=set([('riskmap', 'descriptor')]),
        ),
        migrations.AlterUniqueTogether(
            name='likelyhood',
            unique_together=set([('riskmap', 'descriptor')]),
        ),
    ]
