# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-27 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0010_auto_20160927_1519'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Likelyhood',
            new_name='Likelihood',
        ),
    ]
