# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0010_auto_20160718_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processenablers',
            name='process',
        ),
        migrations.RemoveField(
            model_name='processenablers',
            name='scenario',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='process_enablers',
        ),
        migrations.DeleteModel(
            name='ProcessEnablers',
        ),
    ]
