# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0010_auto_20160614_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('is_template', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='impact',
            name='riskmap',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='risk.RiskMap'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='likelyhood',
            name='riskmap',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='risk.RiskMap'),
            preserve_default=False,
        ),
    ]
