# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0012_auto_20160718_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processenabler',
            name='process',
        ),
        migrations.RemoveField(
            model_name='processenabler',
            name='scenario',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='process_enabler',
        ),
        migrations.DeleteModel(
            name='ProcessEnabler',
        ),
    ]
