# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-29 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0015_merge'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='impact',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='impact',
            name='riskmap',
        ),
        migrations.AlterUniqueTogether(
            name='likelihood',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='likelihood',
            name='riskmap',
        ),
        migrations.DeleteModel(
            name='Impact',
        ),
        migrations.DeleteModel(
            name='Likelihood',
        ),
        migrations.DeleteModel(
            name='RiskMap',
        ),
    ]
