# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-29 11:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0016_auto_20160929_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riskmap_id', models.IntegerField(auto_created=True)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('risk_type', models.CharField(blank=True, choices=[('S', 'Strategic'), ('F', 'Financial'), ('O', 'Operational'), ('C', 'Compliance')], max_length=1, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('axis_type', models.CharField(choices=[('I', 'Impact'), ('L', 'Likelihood')], max_length=1)),
                ('position', models.IntegerField(validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(9)])),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('descriptor', models.CharField(max_length=30)),
                ('definition', models.TextField()),
                ('is_template', models.BooleanField(default=False)),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='risk.Company')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='riskmap',
            unique_together=set([('company_id', 'riskmap_id', 'risk_type', 'position')]),
        ),
    ]
