# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-29 11:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0017_auto_20160929_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskmap',
            name='position',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9)]),
        ),
    ]
