# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-29 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0018_auto_20160929_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riskmap',
            old_name='company_id',
            new_name='company',
        ),
        migrations.AlterUniqueTogether(
            name='riskmap',
            unique_together=set([('company', 'riskmap_id', 'risk_type', 'position')]),
        ),
    ]
