# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-29 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0019_auto_20160929_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riskmap',
            options={'ordering': ('company', 'risk_type', 'name', 'axis_type', 'position')},
        ),
        migrations.AlterUniqueTogether(
            name='riskmap',
            unique_together=set([('company', 'riskmap_id', 'risk_type', 'axis_type', 'position')]),
        ),
    ]
