# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-11 10:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0020_auto_20160929_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskmap',
            name='level',
            field=models.IntegerField(choices=[('S', 'Strategic'), ('F', 'Financial'), ('O', 'Operational'), ('C', 'Compliance')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='riskmap',
            name='position',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
