# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-11 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0021_auto_20161011_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskmap',
            name='level',
            field=models.IntegerField(choices=[(0, 'TEMPLATE'), (1, 'ENTERPRISE'), (2, 'RISK TYPE'), (3, 'RISK CATEGORY')]),
        ),
    ]
