# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-19 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0022_auto_20161011_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariocategory',
            name='risk_scenario',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scenariocategory',
            name='threat_type',
            field=models.CharField(blank=True, choices=[('Malicious', 'Malicious'), ('Accidental', 'Accidental'), ('Error', 'Error'), ('Failure', 'Failure'), ('Natural', 'Natural'), ('External requirement', 'External requirement')], help_text='The nature of the event', max_length=100),
        ),
    ]
