# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-20 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0023_auto_20161019_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariocategory',
            name='actor',
            field=models.CharField(blank=True, help_text='\n    Who or what triggers the threat that exploits a vulnerability.\n    ', max_length=100),
        ),
        migrations.AddField(
            model_name='scenariocategory',
            name='event',
            field=models.CharField(blank=True, help_text='\n    Something happened that was not supposed to happen,\n    something does not happen that was supposed to happen,\n    or a change in circumstances.\n    Events always have causes and usually have consequences.\n    A consequence is the outcome of an event and has an impact on objectives.\n    ', max_length=100),
        ),
        migrations.AlterField(
            model_name='scenariocategory',
            name='threat_type',
            field=models.CharField(blank=True, help_text='The nature of the event', max_length=100),
        ),
    ]
