# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-20 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0024_auto_20161020_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariocategory',
            name='asset',
            field=models.CharField(blank=True, help_text='\n    An asset is something of either tangible or intangible value\n    that is worth protecting, including people, systems,\n    infrastructure, finances and reputation.\n    ', max_length=100),
        ),
        migrations.AddField(
            model_name='scenariocategory',
            name='resource',
            field=models.CharField(blank=True, help_text='\n    A resource is anything that helps to achieve a goal.\n    ', max_length=100),
        ),
    ]
