# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-20 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0025_auto_20161020_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enabler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50)),
                ('contribution_to_response', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='scenariocategory',
            name='detection',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='scenariocategory',
            name='duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='scenariocategory',
            name='time_lag',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='scenariocategory',
            name='timing',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
