# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-21 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0026_auto_20161020_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processenabler',
            name='freq_effect',
        ),
        migrations.RemoveField(
            model_name='processenabler',
            name='impact_effect',
        ),
        migrations.RemoveField(
            model_name='processenabler',
            name='is_essential_control',
        ),
        migrations.RemoveField(
            model_name='processenabler',
            name='scenario',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='process_enabler',
        ),
        migrations.AddField(
            model_name='enabler',
            name='scenario_category',
            field=models.ForeignKey(default='01', on_delete=django.db.models.deletion.CASCADE, to='risk.ScenarioCategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processenabler',
            name='scenario_category',
            field=models.ForeignKey(default='01', on_delete=django.db.models.deletion.CASCADE, to='risk.ScenarioCategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scenariocategory',
            name='process_enabler',
            field=models.ManyToManyField(through='risk.ProcessEnabler', to='risk.ControlPractice'),
        ),
    ]
