# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-21 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0027_auto_20161021_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='enabler',
            name='type',
            field=models.IntegerField(choices=[(1, 'Principles, Policies and Frameworks Enabler'), (2, 'Organisational Structures Enabler'), (3, 'Culture, Ethics and Behaviour Enabler'), (4, 'Information Enabler'), (5, 'Services, Infrastructure and Applications Enabler'), (6, 'People, Skills and Competencies Enabler')], default=1),
            preserve_default=False,
        ),
    ]
