# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-21 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0028_enabler_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_type', models.CharField(max_length=100)),
                ('impact', models.CharField(choices=[('N', 'N/A'), ('P', 'Primary'), ('S', 'Secondary')], default='N', max_length=1)),
                ('scenario_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.ScenarioCategory')),
            ],
        ),
    ]
