# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-21 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0029_risktype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenariocategory',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='scenariocategory',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='scenariocategory',
            name='detection',
        ),
        migrations.RemoveField(
            model_name='scenariocategory',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='scenariocategory',
            name='event',
        ),
        migrations.RemoveField(
            model_name='scenariocategory',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='scenariocategory',
            name='threat_type',
        ),
        migrations.RemoveField(
            model_name='scenariocategory',
            name='time_lag',
        ),
        migrations.RemoveField(
            model_name='scenariocategory',
            name='timing',
        ),
    ]
