# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-28 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0030_auto_20161021_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioCategoryAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threat_type', models.CharField(blank=True, help_text='The nature of the event', max_length=100)),
                ('actor', models.CharField(blank=True, help_text='\n    Who or what triggers the threat that exploits a vulnerability.\n    ', max_length=100)),
                ('event', models.CharField(blank=True, help_text='\n    Something happened that was not supposed to happen,\n    something does not happen that was supposed to happen,\n    or a change in circumstances.\n    Events always have causes and usually have consequences.\n    A consequence is the outcome of an event and has an impact on objectives.\n    ', max_length=100)),
                ('asset', models.CharField(blank=True, help_text='\n    An asset is something of either tangible or intangible value\n    that is worth protecting, including people, systems,\n    infrastructure, finances and reputation.\n    ', max_length=100)),
                ('resource', models.CharField(blank=True, help_text='\n    A resource is anything that helps to achieve a goal.\n    ', max_length=100)),
                ('timing', models.CharField(blank=True, max_length=100)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('detection', models.CharField(blank=True, max_length=100)),
                ('time_lag', models.CharField(blank=True, max_length=100)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.Company')),
                ('scenario_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.ScenarioCategory')),
            ],
        ),
    ]
