# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-31 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0033_auto_20161028_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='risktype',
            old_name='risk_type',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='risktype',
            name='scenario_category',
        ),
        migrations.RemoveField(
            model_name='scenariocategoryanswer',
            name='risk_type_answer',
        ),
        migrations.AddField(
            model_name='scenariocategory',
            name='risk_types',
            field=models.ManyToManyField(to='risk.RiskType'),
        ),
    ]
