# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-31 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0034_auto_20161031_1153'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='risktypeanswer',
            unique_together=set([('risk_type', 'scenario_category_answer')]),
        ),
    ]
