# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-01 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0035_auto_20161031_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenariocategory',
            name='risk_types',
            field=models.ManyToManyField(blank=True, to='risk.RiskType'),
        ),
    ]
