# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-01 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0036_auto_20161101_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risktypeanswer',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
