# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-02 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0038_auto_20161102_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariocategory',
            name='process_enabler1',
            field=models.ManyToManyField(related_name='process_enablers', to='risk.ControlPractice'),
        ),
    ]
