# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-02 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0040_remove_scenariocategory_process_enabler'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scenariocategory',
            old_name='process_enabler1',
            new_name='process_enabler',
        ),
    ]
