# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-02 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0041_auto_20161102_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processenabler',
            name='practice',
        ),
        migrations.RemoveField(
            model_name='processenabler',
            name='scenario_category',
        ),
        migrations.DeleteModel(
            name='ProcessEnabler',
        ),
    ]
