# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-02 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0044_auto_20161102_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenariocategory',
            name='process_enabler',
        ),
        migrations.AddField(
            model_name='scenariocategory',
            name='process_enablers',
            field=models.ManyToManyField(blank=True, to='risk.ControlPractice'),
        ),
        migrations.AlterUniqueTogether(
            name='processenableranswer',
            unique_together=set([('control_practice', 'scenario_category_answer')]),
        ),
    ]
