# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-03 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0045_auto_20161102_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnablerAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_on_frequency', models.CharField(blank=True, choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], max_length=1)),
                ('effect_on_impact', models.CharField(blank=True, choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], max_length=1)),
                ('essential_control', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N')], max_length=1)),
                ('enabler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.Enabler')),
                ('scenario_category_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.ScenarioCategoryAnswer')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='enableranswer',
            unique_together=set([('enabler', 'scenario_category_answer')]),
        ),
    ]
