# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-04 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0046_auto_20161103_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenariocategoryanswer',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='scenariocategoryanswer',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
