# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-08 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0047_auto_20161104_1028'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SelectionControl',
            new_name='ControlSelection',
        ),
    ]
