# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-08 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0048_auto_20161108_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('Q', 'Periodic'), ('P', 'Project'), ('C', 'Change')], max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.Company')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set([('name', 'company')]),
        ),
    ]
