# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-09 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0049_auto_20161108_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariocategoryanswer',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='risk.Project'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='scenariocategoryanswer',
            unique_together=set([('project', 'scenario_category')]),
        ),
    ]
