# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-09 08:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0050_auto_20161109_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenariocategoryanswer',
            name='name',
        ),
    ]
