# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-09 08:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0051_remove_scenariocategoryanswer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenariocategoryanswer',
            name='company',
        ),
    ]
