# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-13 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0052_remove_scenariocategoryanswer_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlselection',
            name='response',
            field=models.CharField(choices=[('N', 'No selection'), ('A', 'Accept'), ('M', 'Mitigate'), ('T', 'Transfer'), ('O', 'Avoid')], default='N', max_length=1),
        ),
    ]
