# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-15 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0053_auto_20161113_2223'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='riskmap',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='riskmap',
            name='company',
        ),
        migrations.DeleteModel(
            name='RiskMap',
        ),
    ]
