# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-15 16:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0054_auto_20161115_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.IntegerField(choices=[(0, 'TEMPLATE'), (1, 'ENTERPRISE'), (2, 'RISK TYPE'), (3, 'RISK CATEGORY')])),
                ('risk_type', models.CharField(blank=True, choices=[('S', 'Strategic'), ('F', 'Financial'), ('O', 'Operational'), ('C', 'Compliance')], max_length=1, null=True)),
                ('is_template', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='risk.Company')),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='risk.RiskMap')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RiskMapValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axis_type', models.CharField(choices=[('I', 'Impact'), ('L', 'Likelihood')], max_length=1)),
                ('position', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('descriptor', models.CharField(max_length=30)),
                ('definition', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('risk_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.RiskMap')),
            ],
            options={
                'ordering': ('risk_map', 'axis_type', 'position'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='riskmapvalue',
            unique_together=set([('risk_map', 'axis_type', 'position')]),
        ),
        migrations.AlterUniqueTogether(
            name='riskmap',
            unique_together=set([('company', 'name')]),
        ),
    ]
