# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-18 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0056_software'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.Company')),
            ],
        ),
        migrations.AlterModelOptions(
            name='software',
            options={'verbose_name_plural': 'Software'},
        ),
    ]
