# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0060_auto_20161118_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'verbose_name_plural': 'Processes'},
        ),
        migrations.RenameField(
            model_name='riskmap',
            old_name='parent_id',
            new_name='parent',
        ),
        migrations.AlterField(
            model_name='processenableranswer',
            name='essential_control',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1),
        ),
        migrations.AlterField(
            model_name='riskmap',
            name='risk_type',
            field=models.CharField(blank=True, choices=[('S', 'STRATEGIC'), ('F', 'FINANCIAL'), ('O', 'OPERATIONAL'), ('C', 'COMPLIANCE')], max_length=1, null=True),
        ),
    ]
