# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0061_auto_20161202_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cia_type', models.CharField(choices=[('C', 'Confidentiality'), ('I', 'Integrity'), ('A', 'Availability')], max_length=1)),
                ('level', models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Very High')])),
                ('description', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.Company')),
            ],
            options={
                'ordering': ('company', 'cia_type', 'level'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='software',
            unique_together=set([('company', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='impact',
            unique_together=set([('company', 'cia_type', 'level')]),
        ),
    ]
