# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0062_auto_20161202_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='software',
            field=models.ManyToManyField(to='risk.Software'),
        ),
        migrations.AlterField(
            model_name='impact',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
