# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0065_auto_20161206_2258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('company', 'name')},
        ),
        migrations.AlterField(
            model_name='department',
            name='software',
            field=models.ManyToManyField(blank=True, to='risk.Software'),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('Q', 'Company'), ('P', 'Project'), ('C', 'Change')], max_length=1),
        ),
        migrations.AlterField(
            model_name='riskmapvalue',
            name='risk_map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='risk.RiskMap'),
        ),
    ]
