# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0066_auto_20161211_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_statement', models.CharField(blank=True, max_length=150)),
                ('last_assessment', models.DateField(verbose_name='Date of last risk assessment')),
                ('next_assessment', models.DateField(verbose_name='Due date for update of risk assessment')),
                ('risk_category', models.CharField(choices=[('S', 'Strategic'), ('D', 'Project Delivery'), ('O', 'Operational')], max_length=1)),
                ('risk_classification', models.IntegerField(choices=[(2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Very High')])),
                ('risk_response', models.CharField(choices=[('A', 'Accept'), ('M', 'Mitigate'), ('T', 'Transfer'), ('O', 'Avoid')], max_length=1)),
                ('risk_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.Employee')),
            ],
        ),
        migrations.AlterField(
            model_name='software',
            name='is_saas',
            field=models.BooleanField(default=False, verbose_name='Is SAAS'),
        ),
    ]
