# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0067_auto_20170224_1109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='software',
            options={'ordering': ('name',), 'verbose_name_plural': 'Software'},
        ),
        migrations.AlterField(
            model_name='enabler',
            name='reference',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='register',
            name='risk_category',
            field=models.CharField(choices=[('S', 'Strategic'), ('D', 'Project Delivery'), ('O', 'Operational')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='register',
            name='risk_classification',
            field=models.IntegerField(choices=[(2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Very High')], default=0),
        ),
        migrations.AlterField(
            model_name='register',
            name='risk_response',
            field=models.CharField(choices=[('A', 'Accept'), ('M', 'Mitigate'), ('T', 'Transfer'), ('O', 'Avoid')], default='A', max_length=1),
        ),
    ]
