# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0068_auto_20170228_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlPracticeRACI',
            fields=[
                ('controlpractice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='risk.ControlPractice')),
                ('board', models.CharField(blank=True, choices=[('', 'No choice'), ('R', 'Responsible'), ('A', 'Accountable'), ('C', 'Consulted'), ('I', 'Informed')], max_length=1, verbose_name='Board')),
                ('chief_executive_officer', models.CharField(blank=True, choices=[('', 'No choice'), ('R', 'Responsible'), ('A', 'Accountable'), ('C', 'Consulted'), ('I', 'Informed')], max_length=1, verbose_name='Chief Executive Officer')),
                ('chief_financial_officer', models.CharField(blank=True, choices=[('', 'No choice'), ('R', 'Responsible'), ('A', 'Accountable'), ('C', 'Consulted'), ('I', 'Informed')], max_length=1, verbose_name='Chief Financial Officer')),
                ('chief_operating_officer', models.CharField(blank=True, choices=[('', 'No choice'), ('R', 'Responsible'), ('A', 'Accountable'), ('C', 'Consulted'), ('I', 'Informed')], max_length=1, verbose_name='Chief Operating Officer')),
                ('business_executives', models.CharField(blank=True, choices=[('', 'No choice'), ('R', 'Responsible'), ('A', 'Accountable'), ('C', 'Consulted'), ('I', 'Informed')], max_length=1, verbose_name='Business Executives')),
                ('business_process_owners', models.CharField(blank=True, choices=[('', 'No choice'), ('R', 'Responsible'), ('A', 'Accountable'), ('C', 'Consulted'), ('I', 'Informed')], max_length=1, verbose_name='Business Process Owners')),
                ('strategy_executive_committee', models.CharField(blank=True, choices=[('', 'No choice'), ('R', 'Responsible'), ('A', 'Accountable'), ('C', 'Consulted'), ('I', 'Informed')], max_length=1, verbose_name='Strategy Executive Committee')),
                ('steering_committee', models.CharField(blank=True, choices=[('', 'No choice'), ('R', 'Responsible'), ('A', 'Accountable'), ('C', 'Consulted'), ('I', 'Informed')], max_length=1, verbose_name='Steering (Programmes/Projects) Committee')),
                ('project_management_office', models.CharField(blank=True, choices=[('', 'No choice'), ('R', 'Responsible'), ('A', 'Accountable'), ('C', 'Consulted'), ('I', 'Informed')], max_length=1, verbose_name='Project Management Office')),
                ('value_management_office', models.CharField(blank=True, choices=[('', 'No choice'), ('R', 'Responsible'), ('A', 'Accountable'), ('C', 'Consulted'), ('I', 'Informed')], max_length=1, verbose_name='Value Management Office')),
                ('chief_risk_officer', models.CharField(blank=True, choices=[('', 'No choice'), ('R', 'Responsible'), ('A', 'Accountable'), ('C', 'Consulted'), ('I', 'Informed')], max_length=1, verbose_name='Chief Risk Officer')),
                ('chief_information_security_officer', models.CharField(blank=True, choices=[('', 'No choice'), ('R', 'Responsible'), ('A', 'Accountable'), ('C', 'Consulted'), ('I', 'Informed')], max_length=1, verbose_name='Chief Information Security Officer')),
                ('architecture_board', models.CharField(blank=True, choices=[('', 'No choice'), ('R', 'Responsible'), ('A', 'Accountable'), ('C', 'Consulted'), ('I', 'Informed')], max_length=1, verbose_name='Architecture Board')),
                ('enterprice_risk_committee', models.CharField(blank=True, choices=[('', 'No choice'), ('R', 'Responsible'), ('A', 'Accountable'), ('C', 'Consulted'), ('I', 'Informed')], max_length=1, verbose_name='Enterprice Risk Committee')),
                ('head_human_resources', models.CharField(blank=True, choices=[('', 'No choice'), ('R', 'Responsible'), ('A', 'Accountable'), ('C', 'Consulted'), ('I', 'Informed')], max_length=1, verbose_name='Head Human Resources')),
                ('compliance', models.CharField(blank=True, choices=[('', 'No choice'), ('R', 'Responsible'), ('A', 'Accountable'), ('C', 'Consulted'), ('I', 'Informed')], max_length=1, verbose_name='Compliance')),
                ('audit', models.CharField(blank=True, choices=[('', 'No choice'), ('R', 'Responsible'), ('A', 'Accountable'), ('C', 'Consulted'), ('I', 'Informed')], max_length=1, verbose_name='Audit')),
                ('chief_information_officer', models.CharField(blank=True, choices=[('', 'No choice'), ('R', 'Responsible'), ('A', 'Accountable'), ('C', 'Consulted'), ('I', 'Informed')], max_length=1, verbose_name='Chief Information Officer')),
                ('head_architect', models.CharField(blank=True, choices=[('', 'No choice'), ('R', 'Responsible'), ('A', 'Accountable'), ('C', 'Consulted'), ('I', 'Informed')], max_length=1, verbose_name='Head Architect')),
                ('head_development', models.CharField(blank=True, choices=[('', 'No choice'), ('R', 'Responsible'), ('A', 'Accountable'), ('C', 'Consulted'), ('I', 'Informed')], max_length=1, verbose_name='Head Development')),
                ('head_it_operations', models.CharField(blank=True, choices=[('', 'No choice'), ('R', 'Responsible'), ('A', 'Accountable'), ('C', 'Consulted'), ('I', 'Informed')], max_length=1, verbose_name='Head IT Operations')),
                ('head_it_administration', models.CharField(blank=True, choices=[('', 'No choice'), ('R', 'Responsible'), ('A', 'Accountable'), ('C', 'Consulted'), ('I', 'Informed')], max_length=1, verbose_name='Head IT Administration')),
                ('service_manager', models.CharField(blank=True, choices=[('', 'No choice'), ('R', 'Responsible'), ('A', 'Accountable'), ('C', 'Consulted'), ('I', 'Informed')], max_length=1, verbose_name='Service Manager')),
                ('information_security_manager', models.CharField(blank=True, choices=[('', 'No choice'), ('R', 'Responsible'), ('A', 'Accountable'), ('C', 'Consulted'), ('I', 'Informed')], max_length=1, verbose_name='Information Security Manager')),
                ('business_continuity_manager', models.CharField(blank=True, choices=[('', 'No choice'), ('R', 'Responsible'), ('A', 'Accountable'), ('C', 'Consulted'), ('I', 'Informed')], max_length=1, verbose_name='Business Continuity Manager')),
                ('privacy_officer', models.CharField(blank=True, choices=[('', 'No choice'), ('R', 'Responsible'), ('A', 'Accountable'), ('C', 'Consulted'), ('I', 'Informed')], max_length=1, verbose_name='Privacy Officer')),
            ],
        ),
    ]
