# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0069_controlpracticeraci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlpracticeraci',
            name='steering_committee',
            field=models.CharField(blank=True, choices=[('', 'No choice'), ('R', 'Responsible'), ('A', 'Accountable'), ('C', 'Consulted'), ('I', 'Informed')], max_length=1, verbose_name='Steering Committee'),
        ),
    ]
