# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0070_auto_20170320_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controlpracticeraci',
            options={'verbose_name_plural': 'Practice RACIs'},
        ),
    ]
