# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 10:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0071_auto_20170511_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='enableranswer',
            name='percentage_complete',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% complete'),
        ),
        migrations.AddField(
            model_name='processenableranswer',
            name='percentage_complete',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% complete'),
        ),
    ]
