# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 12:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import risk.models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0072_auto_20170912_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='avatar_color',
            field=models.CharField(default=risk.models.get_avatar_color, max_length=7),
        ),
        migrations.AddField(
            model_name='employee',
            name='initials',
            field=models.CharField(default='', max_length=2, validators=[django.core.validators.RegexValidator(message="Must be exactly 2 alphanumeric uppercase characters (e.g. 'DM')", regex='^[A-Z]{2}$')]),
        ),
    ]
