# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 12:40
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0073_auto_20170927_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenariocategoryanswer',
            name='threat_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Malicious'), (2, 'Accidental'), (3, 'Error'), (4, 'Failure'), (5, 'Natural'), (6, 'External requirement')], help_text='The nature of the event', max_length=11),
        ),
    ]
