# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 20:11
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0078_auto_20171128_1344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enableranswer',
            options={'ordering': ['enabler']},
        ),
        migrations.AlterModelOptions(
            name='processenableranswer',
            options={'ordering': ['control_practice']},
        ),
        migrations.AlterModelOptions(
            name='risktypeanswer',
            options={'ordering': ['risk_type']},
        ),
        migrations.AlterField(
            model_name='scenariocategoryanswer',
            name='actor',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Internal'), (2, 'External'), (3, 'Human'), (4, 'Non-human')], help_text='\n    Who or what triggers the threat that exploits a vulnerability.\n    ', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='scenariocategoryanswer',
            name='asset',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Process'), (2, 'People and Skills'), (3, 'Organizational Structure'), (4, 'Physical Infrastructure'), (5, 'IT Infrastructure'), (6, 'Information'), (7, 'Applications')], help_text='\n    An asset is something of either tangible or intangible value\n    that is worth protecting, including people, systems,\n    infrastructure, finances and reputation.\n    ', max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='scenariocategoryanswer',
            name='event',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Disclosure'), (2, 'Interruption'), (3, 'Modification'), (4, 'Theft'), (5, 'Destruction'), (6, 'Ineffective design'), (7, 'Ineffective execution'), (8, 'Rules and regulations'), (9, 'Inappropriate use')], help_text='\n    Something happened that was not supposed to happen,\n    something does not happen that was supposed to happen,\n    or a change in circumstances.\n    Events always have causes and usually have consequences.\n    A consequence is the outcome of an event and has an impact on objectives.\n    ', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='scenariocategoryanswer',
            name='resource',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Process'), (2, 'People and Skills'), (3, 'Organizational Structure'), (4, 'Physical Infrastructure'), (5, 'IT Infrastructure'), (6, 'Information'), (7, 'Applications')], help_text='\n    A resource is anything that helps to achieve a goal.\n    ', max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='scenariocategoryanswer',
            name='threat_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Malicious'), (2, 'Accidental'), (3, 'Error'), (4, 'Failure'), (5, 'Natural'), (6, 'External requirement')], help_text='The nature of the event', max_length=11, null=True),
        ),
    ]
