# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-06 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0079_auto_20171210_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enableranswer',
            name='essential_control',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1),
        ),
    ]
