# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-06 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0080_auto_20180206_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariocategoryanswer',
            name='gross_frequency',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='scenariocategoryanswer',
            name='gross_impact',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
