# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-15 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0081_auto_20180206_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariocategoryanswer',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
