# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-15 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0082_scenariocategoryanswer_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('Q', 'Company'), ('P', 'Project'), ('C', 'Change'), ('D', 'Default')], max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='scenariocategoryanswer',
            unique_together=set([('project', 'scenario_category', 'is_default')]),
        ),
    ]
