# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-10 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0084_auto_20180220_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='standards',
            field=models.ManyToManyField(to='risk.Standard'),
        ),
    ]
