# Generated by Django 2.1.5 on 2019-02-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0085_auto_20180310_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlpractice',
            name='practice_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='controlpractice',
            name='practice_name_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='controlpractice',
            name='practice_name_nl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='selection',
            name='standards',
            field=models.ManyToManyField(limit_choices_to={'is_active': True}, to='risk.Standard'),
        ),
    ]
